### PR TITLE
FIX: alignment consistency issue

### LINKED ISSUE #347: The alignment of the question with the subjective answer input box is off in preview
Reference image:

MCQ (correct)
Screenshot 2021-06-19 at 1 58 59 PM

Subjective (incorrect)
Screenshot 2021-06-19 at 1 59 02 PM

### PR DESCRIPTION
**Pull request by dalmia**
Fixes #347 

## Test Plan

- [x] Test Responsiveness
    - [x] Laptop (1200px)
    - [x] Tablet (760px)
    - [x] Phone (320px)
- [x] Cross-Browser Testing
    - [x] Chrome
    - [x] Firefox
    - [x] Safari
- [ ] Local Language Support
- [ ] Wrote tests
- [x] Tested locally
- [x] Tested on staging
- [x] Tested on phone
- [ ] Tested on production

### CODE REVIEW

File: src/components/Items/Question/Body.vue [hunk 1]
```diff
@@ -220,19 +221,27 @@ export default {
   },
   computed: {
     ...mapState("sync", ["pending"]),
+    subjectiveAnswerClass() {
```
Comment (dalmia) [inline src/components/Items/Question/Body.vue:224]: combine this with the non-computed class in template
