### PR TITLE
FIX: bug fix and error handling

### LINKED ISSUE #510: Missing undefined check and unhandled else condition in SSO code

### LINKED ISSUE #511: BUG: incorrect authentication header leading to errors in ChromeWebview
Example - https://sentry.io/organizations/avanti-fellows-af/issues/2667569042/?project=5828567&query=is%3Aunresolved&sort=freq&statsPeriod=14d

Screenshot 2021-11-03 at 7 05 06 PM

This is happening in some older browsers because in our RootClient.js code, the bearer token has a `\n` in the starting of the string

Screenshot 2021-11-03 at 7 59 59 PM

### PR DESCRIPTION
**Pull request by deepansh96**
Fixes #510 
Fixes #511 

## Test Plan

- ~[ ] Test Responsiveness~
   - [ ] Laptop (1200px)
   - [ ] Tablet (760px)
   - [ ] Phone (320px)
- ~[ ] Cross-Browser Testing~
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Safari (use BrowserStack)
- ~[ ] Local Language Support~
- [ ] Wrote tests
- [x] Tested locally
- [x] Self-review
- [x] Comments have been added appropriately
- ~[ ] Check for bundle size [here](https://bundlephobia.com/) if adding a package~
- [x] Added relevant details like Labels/Projects/Milestones etc.
- ~[ ] Images have `alt` attributes~
- ~[ ] Any `target="_blank"` links have `rel="noopener"`~
- ~[ ] Only SVGs are used as images. If PNGs are used, their size has been optimised.~
- [ ] Tested on staging
- ~[ ] Tested on an actual physical phone~
- [ ] Tested on production

### CODE REVIEW

File: src/pages/Embeds/Plio.vue [hunk 1]
```diff
@@ -269,7 +272,7 @@ export default {
               },
             });
             thirdPartyAuthPromiseResolve();
-          }
+          } else this.$router.replace({ name: "404", params: {} });
```
Comment (dalmia) [inline src/pages/Embeds/Plio.vue:275]:
```suggestion
          } else this.$router.replace({ name: "404" });
```

File: src/pages/Embeds/Plio.vue [hunk 2]
```diff
@@ -260,7 +260,10 @@ export default {
           // reload the page and remove the auth query params
           // if the user is authenticated -- they will be able to see the plio
           // if the user is not -- they will be asked to log in and then see the plio
-          if (error.response.status === 400) {
+
+          // if for some reason the API call didn't go through and there's no response
+          // object, then redirect the user to a 404 page
+          if (error.response != undefined && error.response.status === 400) {
```
Comment (dalmia) [inline src/pages/Embeds/Plio.vue:266]: what about `error.response != undefined`
