### PR TITLE
FIX: update 'watching' events instead of re-creating them everytime

### LINKED ISSUE #532: Increase upload interval time from 10 secs to 20 secs

### LINKED ISSUE #533: Update 'watching' events instead of creating everytime
Whenever a session is created, and the user watches a plio, we create new 'watching' events every few seconds. This has added up over the past few months and is now taking 80% of space in the Events table on our database.
This also led to an out of memory error in our data pipeline.

Instead of creating new watching events, just create **one** watching event for each session and keep updating it regularly.

### PR DESCRIPTION
**Pull request by deepansh96**
Fixes #532 
Fixes #533 

## Test Plan

- [ ] ~Test Responsiveness~
   - [ ] Laptop (1200px)
   - [ ] Tablet (760px)
   - [ ] Phone (320px)
- [ ] ~Cross-Browser Testing~
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Safari (use BrowserStack)
- [ ] ~Local Language Support~
- [x] Wrote tests
- [x] Tested locally
- [x] Self-review
- [x] Comments have been added appropriately
- [ ] ~Check for bundle size [here](https://bundlephobia.com/) if adding a package~
- [x] Added relevant details like Labels/Projects/Milestones etc.
- [ ] ~Images have `alt` attributes~
- [ ] ~Any `` tags have `width` and `height` specified~
- [ ] ~Any `target="_blank"` links have `rel="noopener"`~
- [ ] ~Only SVGs are used as images. If PNGs are used, their size has been optimised.~
- [ ] ~Any SVGs without text have their `aria-label` attributes set~
- [ ] Tested on staging
- [ ] ~Tested on an actual physical phone~
- [ ] Tested on production

### CODE REVIEW

File: src/pages/Embeds/Plio.vue [hunk 1]
```diff
@@ -1050,8 +1054,10 @@ export default {
     },
     /**
      * creates a new event
+     * @param {String} eventType - The type of event that needs to be logged
+     * @param {Object} eventDetails - An object with the details of the event
```
Comment (dalmia) [inline src/pages/Embeds/Plio.vue:1058]:
```suggestion
     * @param {Object} eventDetails - details of the event
```

File: src/pages/Embeds/Plio.vue [hunk 2]
```diff
@@ -726,8 +727,11 @@ export default {
       if (this.hasSessionStarted) {
         // update session data
         this.updateSession();
-        // create an event for the user watching the plio
-        this.createEvent("watching");
+        // if a 'watching' event exists for the current session, update that event
+        // else create a new event for the user watching the plio
```
Comment (dalmia) [inline src/pages/Embeds/Plio.vue:731]:
```suggestion
        // else create a new event
```

Comment (dalmia) [inline src/pages/Embeds/Plio.vue:731]:
```suggestion
        // else create a new event
```

File: src/pages/Embeds/Plio.vue (hunk 1 above)
Comment (dalmia) [inline src/pages/Embeds/Plio.vue:1058]:
```suggestion
     * @param {Object} eventDetails - details of the event
```

File: src/pages/Embeds/Plio.vue [hunk 3]
```diff
@@ -1064,7 +1070,24 @@ export default {
...
       };
-      EventAPIService.createEvent(eventData);
+      let response = await EventAPIService.createEvent(eventData);
+      if (eventType == "watching") this.watchingEventDBId = response.id;
+    },
+    /**
+     * Updates an event
+     * @param {String} eventType - The type of event that needs to be logged
+     * @param {Number} eventDBId - The id of an event as pulled from the database which needs to be updated
+     * @param {Object} eventDetails - An object with the details of the event
```
Comment (dalmia) [inline src/pages/Embeds/Plio.vue:1080]:
```suggestion
     * @param {Object} eventDetails - details of the event
```

File: src/pages/Embeds/Plio.vue [hunk 4]
```diff
@@ -1064,7 +1070,24 @@ export default {
...
         session: this.sessionDBId,
       };
-      EventAPIService.createEvent(eventData);
+      let response = await EventAPIService.createEvent(eventData);
+      if (eventType == "watching") this.watchingEventDBId = response.id;
+    },
+    /**
+     * Updates an event
+     * @param {String} eventType - The type of event that needs to be logged
+     * @param {Number} eventDBId - The id of an event as pulled from the database which needs to be updated
```
Comment (dalmia) [inline src/pages/Embeds/Plio.vue:1079]:
```suggestion
     * @param {Number} eventDBId - The id of the event instance which needs to be updated
```

File: src/pages/Embeds/Plio.vue [hunk 5]
```diff
@@ -1064,7 +1070,24 @@ export default {
...
+     * @param {Object} eventDetails - An object with the details of the event
+     */
+    updateEvent(eventType, eventDBId, eventDetails = {}) {
+      if (!this.hasSessionStarted || !this.isAuthenticated || this.previewMode) return;
```
Comment (dalmia) [inline src/pages/Embeds/Plio.vue:1083]: this is not needed as the function invoking this function already places these checks.

File: src/pages/Embeds/Plio.vue [hunk 6]
```diff
@@ -1064,7 +1070,24 @@ export default {
...
+      let eventData = {
```
Comment (dalmia) [inline src/pages/Embeds/Plio.vue:1084]: why create this variable?

File: src/services/API/Event.js [hunk 7]
```diff
@@ -2,6 +2,10 @@ import { apiClient } from "@/services/API/RootClient.js";
 import { eventsEndpoint } from "@/services/API/Endpoints.js";
 
 export default {
+  /**
+   *
+   * @param {Object} eventData - The data that will be used as a payload in the POST request
```
Comment (dalmia) [inline src/services/API/Event.js:7]:
```suggestion
   * @param {Object} eventData - details for the event to be created
```

File: src/services/API/Event.js [hunk 8]
```diff
@@ -10,4 +14,12 @@ export default {
         return response.data;
       });
   },
+  /**
+   *
```
Comment (dalmia) [inline src/services/API/Event.js:18]: description for the method?

File: src/services/API/Event.js [hunk 9]
```diff
@@ -2,6 +2,10 @@ import { apiClient } from "@/services/API/RootClient.js";
 import { eventsEndpoint } from "@/services/API/Endpoints.js";
 
 export default {
+  /**
+   *
```
Comment (dalmia) [inline src/services/API/Event.js:6]: description for the method?

File: src/services/API/Event.js [hunk 10]
```diff
@@ -10,4 +14,12 @@ export default {
         return response.data;
       });
   },
+  /**
+   *
+   * @param {Number} eventId - The ID of the event that needs to be patched
```
Comment (dalmia) [inline src/services/API/Event.js:19]:
```suggestion
   * @param {Number} eventId - The ID of the event that needs to be updated
```

File: src/services/API/Event.js [hunk 11]
```diff
@@ -10,4 +14,12 @@ export default {
...
+   * @param {Object} eventData - The event will be patched with this data
```
Comment (dalmia) [inline src/services/API/Event.js:20]:
```suggestion
   * @param {Object} eventData - The event will be updated with this data
```

File: src/services/API/Event.js [hunk 12]
```diff
@@ -10,4 +14,12 @@ export default {
...
+   */
+  updateEvent(eventId, eventData) {
+    return apiClient().patch(eventsEndpoint + eventId, eventData);
```
Comment (dalmia) [inline src/services/API/Event.js:23]: we are sending the entire event details object, no? then, put will be more appropriate no?

File: tests/unit/pages/embeds/Plio.spec.js [hunk 13]
```diff
@@ -318,4 +319,96 @@ describe("Plio.vue", () => {
...
+    // using the fake response data
+    mockAxios.mockResponse(clonedeep(dummyPublishedPlio), mockAxios.queue()[0]);
+
+    // wait until the DOM updates after promises resolve
+    await flushPromises();
+    // assert that updateEvent method has been called with the correct params
+    expect(updateEvent).toHaveBeenCalledWith("watching", 1);
+  });
+
+  it("makes a PATCH call to update a watching event", () => {
```
Comment (dalmia) [inline tests/unit/pages/embeds/Plio.spec.js:380]:
```suggestion
  it("updates a watching event when updateEvent is called", () => {
```

File: src/pages/Embeds/Plio.vue [hunk 14]
```diff
@@ -191,6 +191,7 @@ export default {
       isScorecardShown: false, // to show the scorecard or not
       plioTitle: "", // title of the plio
       isAspectRatioChecked: false, // whether the check for aspect ratio has been done
+      watchingEventDBId: null, // the DB id of the latest 'watching' event for a given session
```
Comment (dalmia) [inline src/pages/Embeds/Plio.vue:194]: I think there is no other id it can be apart from the DB id - plus you've mentioned it already in the comments.
```suggestion
      watchingEventId: null, // the DB id of the latest 'watching' event for a given session
```

File: tests/unit/pages/embeds/Plio.spec.js [hunk 15]
```diff
@@ -318,4 +319,96 @@ describe("Plio.vue", () => {
...
+    await store.dispatch("auth/setAccessToken", dummyAccessToken);
+
+    mount(Plio, {
+      shallow: true,
+      props: {
+        plioId: plioId,
+      },
+      data() {
+        return {
+          watchingEventDBId: 1,
```
Comment (dalmia) [inline tests/unit/pages/embeds/Plio.spec.js:362]: comment saying that this will simulate the case when watching event was already created

File: tests/unit/pages/embeds/Plio.spec.js [hunk 16]
```diff
@@ -318,4 +319,96 @@ describe("Plio.vue", () => {
...
+    await flushPromises();
+
+    // resolve the `GET` request waiting in the queue (for receiving plio details)
+    // using the fake response data
+    mockAxios.mockResponse(clonedeep(dummyPublishedPlio), mockAxios.queue()[0]);
+
+    // wait until the DOM updates after promises resolve
+    await flushPromises();
+    // assert that updateEvent method has been called with the correct params
+    expect(updateEvent).toHaveBeenCalledWith("watching", 1);
```
Comment (dalmia) [inline tests/unit/pages/embeds/Plio.spec.js:377]: use a variable for the db id and pass it in both the mount and this assertion.

File: tests/unit/pages/embeds/Plio.spec.js [hunk 17]
```diff
@@ -318,4 +319,96 @@ describe("Plio.vue", () => {
...
+    };
+
+    let eventType = "watching";
+    let eventDBId = 1;
+
+    // invoke the method using the local context object and appropriate params
+    Plio.methods.updateEvent.call(localThis, eventType, eventDBId);
+
+    // the updateEvent method inside EventAPIService would've been called
+    // A patch request would've been made with the correct payload
```
Comment (dalmia) [inline tests/unit/pages/embeds/Plio.spec.js:404]: we don't need to explain which request types to expect in the comments - we have not done that for any API request tests + it is fairly obvious from the code + it ties the comment to the implementation (which we'll have to remember to update if we update the method)

**Review by dalmia — CHANGES_REQUESTED** [review]

File: src/pages/Embeds/Plio.vue (hunk 6 above)
Comment (deepansh96) [reply src/pages/Embeds/Plio.vue:1084]: Just followed the style of the method `createEvent`
Also makes it a little more readable. Passing `eventData` to EventAPIService.udpateEvent()` feels more natural and readable.

If we'll get rid of this variable here, then we should do the same in `createEvent` method

File: src/services/API/Event.js (hunk 8 above)
Comment (deepansh96) [reply src/services/API/Event.js:18]: As discussed, skippping it as method name is obvious

File: src/services/API/Event.js (hunk 9 above)
Comment (deepansh96) [reply src/services/API/Event.js:6]: As discussed, skippping it as method name is obvious

File: src/services/API/Event.js (hunk 11 above)
Comment (deepansh96) [reply src/services/API/Event.js:20]: Updated it according to the method `createEvent` above.
Also, I think let's stick with `payload` term. It is generic enough and it makes sense in every API call.

File: src/pages/Embeds/Plio.vue (hunk 6 above)
Comment (dalmia) [reply src/pages/Embeds/Plio.vue:1083]: haan makes sense - let's do that

File: tests/unit/pages/embeds/Plio.spec.js [hunk 18]
```diff
@@ -352,15 +352,19 @@ describe("Plio.vue", () => {
     // set user
     await store.dispatch("auth/setAccessToken", dummyAccessToken);
 
+    // stimulating the case where a 'watching' event has already been created
```
Comment (dalmia) [inline tests/unit/pages/embeds/Plio.spec.js:355]:
```suggestion
    // simulating the case where a 'watching' event has already been created
```

**Review by dalmia — CHANGES_REQUESTED** [review]
