### PR TITLE
Phone number digits can not be entered more than 10 and 0 input invalid

### LINKED ISSUE #602: Phone number input is exceeding the maxLength specified
**Describe the bug**

The length of phone number while entering at login page is exceeding the maxLength specified. 
The files to look at: Login.vue and InputNumber.vue .

**To Reproduce**
1. Go to 'login-Plio'
2. Enter more than 10 digits for the phone number

**Expected behavior**
It should ideally not let user enter more than 10 digit .

**Screenshots**
Capture

### PR DESCRIPTION
**Pull request by Salonichoudhary07**
Fixes #602 

## Summary

The `localvalue.length`  was returning undefined as it was not being converted into a string.
`.toString` function is added to the `localValue` in `keypress` function in `InputNumber.vue`.
`type` of `<input` is changed to `type`  which is a prop and has `default:"tel"` as there were many trailing zeros and the eventual phone number length was going way beyond 10 and it was still marked valid .
`If` condition is added in `keypress` so that any character is not accepted as input. 

## Test Plan

- [ ] ~Test Responsiveness~
   - [ ] Laptop (1200px)
   - [ ] Tablet (760px)
   - [ ] Phone (320px)
- [ ] ~Cross-Browser Testing~
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Safari (use BrowserStack)
- [ ] ~Local Language Support~
- [x] Hygiene and Housekeeping
   - [x] Self-review
   - [x] Comments have been added appropriately
   - [ ] ~Check for bundle size [here](https://bundlephobia.com/) if adding a package~
   - [x] Added relevant details like Labels/Projects/Milestones etc.
   - [ ] ~If adding or removing any environment variable:~
       - [ ] update `docs/ENV.md`
       - [ ] update Github Workflow files
       - [ ] update DockerFile
       - [ ] update the secrets for staging and production
- [ ] Testing
   - [ ] ~Wrote tests~
   - [x] Tested locally
   - [ ] Tested on staging
   - [ ] Tested on an actual physical phone
   - [ ] Tested on production
- [ ] ~Lighthouse Checks~
   - [ ] Images have `alt` attributes
   - [ ] Any `` tags have `width` and `height` specified
   - [ ] Any `target="_blank"` links have `rel="noopener"`
   - [ ] Only SVGs are used as images. If PNGs are used, their size has been optimised.
   - [ ] Any SVGs without text have their `aria-label` attributes set

### CODE REVIEW

File: src/components/UI/Text/InputNumber.vue [hunk 1]
```diff
@@ -147,6 +147,7 @@ export default {
       default: false,
       type: Boolean,
     },
+
```
Comment (dalmia) [inline src/components/UI/Text/InputNumber.vue:150]: this seems to be a change that happened by mistake?

File: src/components/UI/Text/InputNumber.vue [hunk 2]
```diff
@@ -257,7 +258,7 @@ export default {
     },
     keyPress(event) {
       // invoked when a key is pressed
-      if (this.maxLength != null && this.localValue.length == this.maxLength) {
+      if (this.maxLength != null && this.localValue.toString().length == this.maxLength) {
```
Comment (dalmia) [inline src/components/UI/Text/InputNumber.vue:261]: wouldn't it be better to change the localValue to string where it is computed in the first place instead of converting it to string every time?

Comment (Salonichoudhary07) [reply src/components/UI/Text/InputNumber.vue:261]: yes done

Comment (Salonichoudhary07) [reply src/components/UI/Text/InputNumber.vue:261]: returning `localvalue` as a string from get method

File: src/components/UI/Text/InputNumber.vue [hunk 3]
```diff
@@ -152,7 +152,7 @@ export default {
     localValue: {
       // local copy of the value prop
       get() {
-        return this.value;
+        return this.value.toString();
```
Comment (deepansh96) [inline src/components/UI/Text/InputNumber.vue:155]: @dalmia are we sure we should do this?

Reason - 
this is an InputNumber component. The value that the user types in the textbox gets saved as a `Number` data type which makes sense because this is a InputNumber component.

We need to convert it into string only when doing this check `this.localValue.length == this.maxLength`

If we go ahead with converting the `localValue` into string as what Saloni did in her latest commit, then we're forever converting this number into a string and that is what gets emitted into the parent.

Currently it should work fine because we're not using this component anywhere else other than Login page but this doesn't feel correct given this is an inputNumber component. The component should hold an internal data as Number not a string.

**Review by deepansh96 — COMMENTED** [review]
There's one more bug which you can fix in this PR itself @Salonichoudhary07 

When I type mobile number starting 0 in the text box, the text "Mobile number is invalid" doesn't show up. It shows up in all other cases where the number I type starts with 1, 2, 3 ... 9

File: src/components/UI/Text/InputNumber.vue (hunk 3 above)
Comment (deepansh96) [reply src/components/UI/Text/InputNumber.vue:155]: @Salonichoudhary07 I talked to Aman regarding this. He agrees with what I said here. 
The first commit you made, where you did `this.localValue.toString().lenght == this.`, we should do that change.

Also one more point of feedback that Aman asked me to give you, is that, if someone has reviewed your PR and asked something, that doesn't imply that it is the right answer. You should be confident of the change you made and if you're not, play around with things enough so that you're confident. In this case for example, Aman asked a question "If doing that would be better?". So you should defend the changes you've made :p

Comment (Salonichoudhary07) [reply src/components/UI/Text/InputNumber.vue:155]: Yes, I will do that.

File: src/components/UI/Text/InputNumber.vue [hunk 4]
```diff
@@ -173,7 +173,13 @@ export default {
...
     isValidationEnabled() {
       // whether input validation is on
-      return this.validation["enabled"] && this.validationMessage != "";
+      if(this.localValue.toString() == "0")
+      {
+        return this.validationMessage != "";
+      }
+      else{
+        return this.validation["enabled"] && this.validationMessage != "";
+      }
```
Comment (dalmia) [inline src/components/UI/Text/InputNumber.vue:182]: this will still lead to the issue that I can add as many trailing zeros as I want and the eventual phone number length goes way beyond 10 and it is still marked valid (as shown in the image - no error message)

Screenshot 2022-01-31 at 10 18 00 AM

File: src/components/UI/Text/InputNumber.vue [hunk 5]
```diff
@@ -53,7 +53,7 @@
         :class="[inputAreaClass, boxStyling]"
         :min="min"
         :max="max"
-        type="number"
+        type="type"
```
Comment (deepansh96) [inline src/components/UI/Text/InputNumber.vue:56]: Can you help me understand what is this supposed to do?
As far as I remember, There's no "type" type in an HTML `<input>` tag

Comment (deepansh96) [reply src/components/UI/Text/InputNumber.vue:56]: See this - https://www.w3schools.com/html/html_form_input_types.asp

Comment (Salonichoudhary07) [reply src/components/UI/Text/InputNumber.vue:56]: I hope the change answers the question

File: src/components/UI/Text/InputNumber.vue [hunk 6]
```diff
@@ -257,7 +262,14 @@ export default {
     },
     keyPress(event) {
       // invoked when a key is pressed
-      if (this.maxLength != null && this.localValue.length == this.maxLength) {
+      // character key not accepted
+      event = event || window.event;
```
Comment (deepansh96) [inline src/components/UI/Text/InputNumber.vue:266]: What is the purpose of `window.event`?

File: src/components/UI/Text/InputNumber.vue [hunk 7]
```diff
@@ -257,7 +262,14 @@ export default {
...
+      var charCode = (typeof event.which == "undefined") ? event.keyCode : event.which;
```
Comment (deepansh96) [inline src/components/UI/Text/InputNumber.vue:267]: You're using `event.which` here.
If you read the docs for this, they give a warning that this is a non standard and should not be used in production as it's result is highly variable. See this - https://developer.mozilla.org/en-US/docs/Web/API/UIEvent/which

Did you find this piece of code online somewhere? It's okay if you did, but make you understand what's happening.

File: src/components/UI/Text/InputNumber.vue [hunk 8]
```diff
@@ -257,7 +262,14 @@ export default {
...
+      var charStr = String.fromCharCode(charCode);
```
Comment (deepansh96) [inline src/components/UI/Text/InputNumber.vue:268]:
```suggestion
      let charCode = (typeof event.which == "undefined") ? event.keyCode : event.which;
      let charStr = String.fromCharCode(charCode);
```

We should be using `let` here instead of `var`
You can read up on which one to use when

File: src/components/UI/Text/InputNumber.vue (hunk 5 above)
Comment (deepansh96) [inline src/components/UI/Text/InputNumber.vue:56]: prop not bound

File: src/components/UI/Text/InputNumber.vue [hunk 9]
```diff
@@ -106,6 +106,11 @@ export default {
       default: "",
       type: [String, Number],
     },
+    /** the type of the input in the input box */
+    type: { 
+      default: 'tel' ,
```
Comment (deepansh96) [inline src/components/UI/Text/InputNumber.vue:111]: Why this space between `tel` and the comma?

File: src/components/UI/Text/InputNumber.vue [hunk 10]
```diff
@@ -155,7 +160,7 @@ export default {
         return this.value;
       },
       set(localValue) {
-        this.$emit("update:value", localValue);
+       this.$emit("update:value", localValue);
```
Comment (deepansh96) [inline src/components/UI/Text/InputNumber.vue:163]: Always perform a self review before giving a pr to someone else for review. 
All you have to do is go to the "files changed" tab and see your changes yourself. 
You'll figure out these small small issues on your own.
Like here, this removal of space is not necessary here.

**Review by deepansh96 — CHANGES_REQUESTED** [review]

File: src/components/UI/Text/InputNumber.vue (hunk 10 above)
Comment (Salonichoudhary07) [reply src/components/UI/Text/InputNumber.vue:163]: okay

File: src/components/UI/Text/InputNumber.vue (hunk 8 above)
Comment (Salonichoudhary07) [reply src/components/UI/Text/InputNumber.vue:268]: let allows us to declare variables that are limited in scope to the block, statement, or expression on which it is used. 
var keyword is used to define a variable globally, or locally to an entire function regardless of block scope.
Will use let here.

File: src/components/UI/Text/InputNumber.vue (hunk 7 above)
Comment (Salonichoudhary07) [reply src/components/UI/Text/InputNumber.vue:267]: Yes, I did, I went through the code I did not knew about the warning.

File: src/components/UI/Text/InputNumber.vue (hunk 6 above)
Comment (Salonichoudhary07) [reply src/components/UI/Text/InputNumber.vue:266]: It returns the Event which is currently being handled by the site's code, not required here as we are already specifying the event.

File: src/components/UI/Text/InputNumber.vue (hunk 7 above)
Comment (Salonichoudhary07) [reply src/components/UI/Text/InputNumber.vue:267]: Removed it as we only need the keycode to compare the keypress.
Thank you for your feedback, will surely keep these things in mind in the future.

File: src/components/UI/Text/InputNumber.vue [hunk 11]
```diff
@@ -263,9 +263,8 @@ export default {
     keyPress(event) {
       // invoked when a key is pressed
       // character key not accepted
-      event = event || window.event;
-      var charCode = (typeof event.which == "undefined") ? event.keyCode : event.which;
-      var charStr = String.fromCharCode(charCode);
+      let charCode = event.keyCode;
```
Comment (deepansh96) [inline src/components/UI/Text/InputNumber.vue:266]: These things should always be checked. 
`keyCode` is deprecated
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode

**Review by deepansh96 — CHANGES_REQUESTED** [review]

File: src/components/UI/Text/InputNumber.vue (hunk 11 above)
Comment (Salonichoudhary07) [reply src/components/UI/Text/InputNumber.vue:266]: will use event.key will work the same

Comment (Salonichoudhary07) [reply src/components/UI/Text/InputNumber.vue:266]: will use event.key will work the same

File: src/components/UI/Text/InputNumber.vue [hunk 12]
```diff
@@ -257,7 +262,11 @@ export default {
     },
     keyPress(event) {
       // invoked when a key is pressed
-      if (this.maxLength != null && this.localValue.length == this.maxLength) {
+      // character key not accepted
+      if (!/^[0-9]+$/.test(event.key)){
+        event.preventDefault();
+      }
```
Comment (deepansh96) [inline src/components/UI/Text/InputNumber.vue:268]: You can do this in the <input> tag itself. No need to write extra javascript for this
Take a look at this 
https://www.w3schools.com/tags/att_input_pattern.asp

**Review by deepansh96 — CHANGES_REQUESTED** [review]

File: src/components/UI/Text/InputNumber.vue (hunk 12 above)
Comment (Salonichoudhary07) [reply src/components/UI/Text/InputNumber.vue:268]: yes I tried this earlier too it was not working for me

Comment (deepansh96) [reply src/components/UI/Text/InputNumber.vue:268]: Okay no issues then

**Review by dalmia — APPROVED** [review]
