### PR TITLE
FIX: markers not being draggable on phone

### LINKED ISSUE #200: Markers are not clickable and draggable on phone

### PR DESCRIPTION
**Pull request by dalmia**
Fixes #200 

## Summary
- added touch event handers for selecting and dragging markers on phone

## Test Plan
Tested locally.

### CODE REVIEW

File: src/pages/Test.vue [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+    return {
+      value: 10,
+      markerPositions: [40, 100],
+    };
+  },
+  components: {
+    SliderWithMarkers,
+  },
+};
+</script>
```
Comment (deepansh96) [inline src/pages/Test.vue:24]: Can remove?

File: src/router/index.js [hunk 2]
```diff
@@ -12,6 +13,11 @@ const routes = [
       name: "Login",
     },
   },
+  {
+    path: "/test",
+    name: "Test",
+    component: Test,
+  },
```
Comment (deepansh96) [inline src/router/index.js:20]: Remove?

File: src/components/UI/Slider/SliderWithMarkers.vue [hunk 3]
```diff
@@ -38,6 +39,8 @@ export default {
       sliderWidth: null, // width of the slider
       markerWidth: null, // width of one marker
       clickAfterDragEnded: false, // indicates whether a marker click was invoked right after it was dragged
+      touched: false, // whether a touch event has been initiated
+      touchValue: null, // the current position where the touch event took place
```
Comment (deepansh96) [inline src/components/UI/Slider/SliderWithMarkers.vue:43]: can rename this to `touchPosition`

**Review by deepansh96 — CHANGES_REQUESTED** [review]

**Review by deepansh96 — APPROVED** [review]
