### PR TITLE
Removed sorting for "name" column, fixed sorting for "number of viewers" column

### LINKED ISSUE #291: Sorting in home page table is incorrect
After the pagination implementation, the sorting feature (clicking the header of a column will sort the plios according to that column) was breaking and showing incorrect results.

This is because the logic was only sorting for the results already showing in the table and not sorting across all the plios.

FIX: 
- Remove sorting for "name" column for now
- Fix the sorting for "number of viewers" column
- To get the appropriate paginated response from the backend, we will need to hand over the ordering logic to the backend. This will mean that the backend will have to calculate the "unique number of viewers" and return the sorted results in a paginated format. Can not and should not use CubeJS on the backend

### PR DESCRIPTION
**Pull request by deepansh96**
Fixes #291 
Please see the issue linked for more details

## Summary
- user only sees the sorting arrow icon over "number of viewers" and not over "name" column
- user clicks the sorting button and a request to the backend is made asking for the ordered results in a paginated format

## Test Plan

- [x] Responsive
- [x] Tested locally
- [x] Tested on staging
- [ ] Tested on production

### CODE REVIEW

File: src/components/Collections/Table/Table.vue [hunk 1]
```diff
@@ -344,64 +341,41 @@ export default {
...
     },
-    sortBy(key) {
-      // invoked when sorting arrows are clicked on a table column
-      // sortOrder value can be 1(ascending) or -1(descending)
-      // everytime this method is involed, sortOrder for the "key" is toggled
-      this.sortKey = key;
-      this.sortOrders[key] = this.sortOrders[key] * -1;
+    sortBy(columnName) {
+      // toggle the sort order for "number_of_viewers" column
+      // and emit it to the parent (Home.vue)
```
Comment (dalmia) [inline src/components/Collections/Table/Table.vue:349]:
```suggestion
      // and emit it to the parent 
```

File: src/components/Collections/Table/Table.vue [hunk 2]
```diff
@@ -344,64 +341,41 @@ export default {
...
+      if (columnName == "number_of_viewers") {
+        this.numberOfViewersSortOrder = this.numberOfViewersSortOrder * -1;
+        this.$emit("sort-by-number-of-viewers", this.numberOfViewersSortOrder);
```
Comment (dalmia) [inline src/components/Collections/Table/Table.vue:352]: seems too long to me and don't think that is needed.
```suggestion
        this.$emit("sort-num-viewers", this.numberOfViewersSortOrder);
```

File: src/components/Collections/Table/Table.vue [hunk 3]
```diff
@@ -206,11 +202,12 @@ export default {
       // classes for search bar input box
       searchInputBoxClass:
         "w-full text-gray-700 leading-tight p-2 pl-4 focus:outline-none",
+      // sort order for the "number of viewers" column. 1 - ascending, -1 - descending
+      numberOfViewersSortOrder: 1,
```
Comment (dalmia) [inline src/components/Collections/Table/Table.vue:206]: seems too too long to me (generally, Of, For like words are not present in variable names)

```suggestion
      numViewersSortOrder: 1,
```

File: src/pages/Home.vue [hunk 4]
```diff
@@ -112,6 +113,8 @@ export default {
       totalNumberOfPlios: 0, // total number of plios for the user
       numberOfPliosPerPage: 5, // number of plios to show on one page (default: 5)
       searchString: "", // the search string to filter the plios on
+      sortByFields: [], // array containing the fields to sort the plios on
+      currentPageNumber: undefined, // holds the current page number
```
Comment (dalmia) [inline src/pages/Home.vue:117]: I don't see any utility for this?

File: src/pages/Home.vue [hunk 5]
```diff
@@ -142,6 +145,18 @@ export default {
...
+
+      // remove any existing value of "unique_viewers" field. New value will be pushed below
+      this.sortByFields = this.sortByFields.filter((value) => {
+        return !value.includes("unique_viewers");
+      });
+
+      // push the appropriate field name according to the sort order and make the API call
+      this.sortByFields.push(sortOrder == 1 ? "unique_viewers" : "-unique_viewers");
+      await this.fetchPlioIds();
+    },
```
Comment (dalmia) [inline src/pages/Home.vue:159]: why not keep the function as `sortPlios` and take the param to sort by as input (e.g. `unique_viewers`, `-unique_viewers`)? won't have to do the `== 1` check too and keeps it generic.

File: src/pages/Home.vue [hunk 6]
```diff
@@ -142,6 +145,18 @@ export default {
...
     ...mapActions("plioItems", ["purgeAllPlios"]),
     ...mapActions("sync", ["startLoading", "stopLoading"]),
+    async sortByNumberOfViewers(sortOrder) {
+      // invoked when the user clicks the sort icon next to "number of viewers" column
+
+      // remove any existing value of "unique_viewers" field. New value will be pushed below
+      this.sortByFields = this.sortByFields.filter((value) => {
+        return !value.includes("unique_viewers");
+      });
+
```
Comment (dalmia) [inline src/pages/Home.vue:155]: at any point we are sorting by only one thing, no? Or are you saying successive sorting is also applied?

File: src/services/API/Plio.js [hunk 7]
```diff
@@ -64,6 +69,8 @@ export default {
     // add search string query param
     if (searchString != undefined && searchString != "")
       queryParams["search"] = searchString;
+    // add sort by query param
+    if (sortBy.length != 0) queryParams["ordering"] = sortBy.join();
```
Comment (dalmia) [inline src/services/API/Plio.js:73]: does `.join()` automatically add commas?

File: src/pages/Home.vue (hunk 6 above)
Comment (dalmia) [reply src/pages/Home.vue:155]: no multiple sorting - remove lists.
