### PR TITLE
FIX: tooltip text

### LINKED ISSUE #407: Tooltip for video input in draft state is incorrect

### PR DESCRIPTION
**Pull request by dalmia**
Fixes #407 

## Test Plan

- [ ] Test Responsiveness
   - [ ] Laptop (1200px)
   - [ ] Tablet (760px)
   - [ ] Phone (320px)
- [ ] Cross-Browser Testing
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Safari
- [ ] Local Language Support
- [ ] Wrote tests
- [x] Tested locally
- [ ] Tested on staging
- [ ] Tested on an actual physical phone
- [ ] Tested on production
- [ ] Check for bundle size [here](https://bundlephobia.com/) if adding a package
- [ ] Added relevant details like Labels/Projects/Milestones etc.

### CODE REVIEW

File: src/assets/locales/en.js [hunk 1]
```diff
@@ -288,8 +288,8 @@ export default {
           "This plio is currently in draft mode and only accessible to you. To make it publicly accessible, publish the plio",
       },
       video_input: {
-        published: "You cannot edit the video URL in a published plio",
-        draft: "You cannot edit the video URL after you publish",
+        published: "You cannot edit the video link in a published plio",
+        draft: "Add the link to the YouTube video you want to make interactive",
```
Comment (deepansh96) [inline src/assets/locales/en.js:292]:
```suggestion
        draft: "Paste the link of the YouTube video you want to make interactive",
```
