### PR TITLE
FIX: after deleting, sometimes images could not be re-uploaded

### LINKED ISSUE #339: Justify-start instead of justify-center in the editor question preview

### LINKED ISSUE #341: In the ImageUploaderDialog, after selecting an image, and deleting it from the preview, re-selecting an image doesn't work.
This was because after one image was selected, that image file stayed in the component's storage. 

Solution -- whenever the image has been deleted from the preview, re-mount the component so that the local storage of that components gets purged and it can start fresh over again

### PR DESCRIPTION
**Pull request by deepansh96**
Fixes #341 
Fixes #339

## Test Plan

- [ ] Test Responsiveness
    - [ ] Laptop (1200px)
    - [ ] Tablet (760px)
    - [ ] Phone (320px)
- [ ] Cross-Browser Testing
    - [ ] Chrome
    - [ ] Firefox
    - [ ] Safari
- [ ] Local Language Support
- [ ] Tested locally
- [ ] Tested on phone
- [ ] Tested on staging
- [ ] Tested on production

### CODE REVIEW

File: src/components/Vue2PortedPackages/VueImageUploader.vue [hunk 1]
```diff
@@ -202,10 +205,10 @@ export default {
       this.$emit("change", output);
     },
     emitLoad() {
-      this.$emit("upload");
+      this.$emit("onLoad");
     },
     emitComplete() {
-      this.$emit("complete");
+      this.$emit("onComplete");
```
Comment (dalmia) [inline src/components/Vue2PortedPackages/VueImageUploader.vue:211]: this will become ononComplete like like mouseover becomes onmouseover. Any reason to change this? instead of staying consistent with others like `input`, `change` (and not `onInput`, `onChange`)

File: src/components/Vue2PortedPackages/VueImageUploader.vue [hunk 2]
```diff
@@ -202,10 +205,10 @@ export default {
       this.$emit("change", output);
     },
     emitLoad() {
-      this.$emit("upload");
+      this.$emit("onLoad");
```
Comment (dalmia) [inline src/components/Vue2PortedPackages/VueImageUploader.vue:208]: same comment as `onComplete`

File: src/components/UI/Alert/ImageUploaderDialog.vue [hunk 3]
```diff
@@ -23,9 +23,18 @@
...
+          v-if="pending"
+          :src="getIconSource('spinner-solid.svg')"
+          class="animate-spin w-1/6 h-1/6 m-auto text-primary"
+        ></inline-svg>
+
+        <!-- image icon svg -->
+        <inline-svg
+          v-else
+          :src="getIconSource('add_image.svg')"
+          class="transform -rotate-12 w-2/3 h-2/3 m-auto text-primary"
```
Comment (dalmia) [inline src/components/UI/Alert/ImageUploaderDialog.vue:37]: any reason for this change?

File: src/components/UI/Alert/ImageUploaderDialog.vue [hunk 4]
```diff
@@ -44,6 +53,7 @@
         accept="image/*"
         @input="loadAndPreviewImage"
         :class="uploaderInputClass"
+        :key="reRenderKey"
```
Comment (dalmia) [inline src/components/UI/Alert/ImageUploaderDialog.vue:56]: what does this do? and how does this help during image deletion?

File: src/components/UI/Alert/ImageUploaderDialog.vue [hunk 5]
```diff
@@ -193,7 +188,6 @@ export default {
       // save the image info locally
       // extract the base64 URL from the info and
       // use it to show the preview
-      this.startLoading();
```
Comment (dalmia) [inline src/components/UI/Alert/ImageUploaderDialog.vue:196]: why move this inside VueImageUploader? That is like changing an imported component with our custom code right? can we avoid it?
