### PR TITLE
NEW: mixpanel phone fixed

### LINKED ISSUE #362: Mixpanel user phone not being tracked

### PR DESCRIPTION
**Pull request by dalmia**
Fixes #362 

## Test Plan

- [ ] ~Test Responsiveness~
   - [ ] Laptop (1200px)
   - [ ] Tablet (760px)
   - [ ] Phone (320px)
- [ ] ~Cross-Browser Testing~
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Safari
- [ ] ~Local Language Support~
- [ ] ~Wrote tests~
- [x] Tested locally
- [ ] Tested on staging
- [ ] ~Tested on an actual physical phone~
- [ ] Tested on production
- [ ] ~Check for bundle size [here](https://bundlephobia.com/) if adding a package~
- [x] Added relevant details like Labels/Projects/Milestones etc.

### CODE REVIEW

File: src/App.vue [hunk 1]
```diff
@@ -162,10 +192,10 @@ export default {
...
           this.$mixpanel.alias(this.user.id.toString());
           this.$mixpanel.people.set({
-            "$first_name": this.user.first_name,
-            "$last_name": this.user.last_name,
-            "$email": this.user.email,
-            "$phone": this.user.phone,
+            $first_name: this.user.first_name,
+            $last_name: this.user.last_name,
+            $email: this.user.email,
+            $phone: this.user.mobile,
```
Comment (deepansh96) [inline src/App.vue:198]: ye $first_name and other variables, linter ki wajah se fatt gaya

Comment (deepansh96) [reply src/App.vue:198]: App.vue mein, turn off the auto save feature of the linter (from the bottom bar), edit this, save this, commit the change, then turn the auto save feature on. I do this only for App.vue

**Review by deepansh96 — CHANGES_REQUESTED** [review]
