### PR TITLE
FIX: make home and login/logout clickable again

### LINKED ISSUE #92: Home and Logout button are not clickable due to overlay
Try using z-index negative

### PR DESCRIPTION
**Pull request by dalmia**
Fixes #92 

## Summary
Remove `overlay` and use `display=flex` with hack of showing the locale switcher on both sides and making the one on the left invisible. Couldn't figure out any other way of doing this. 

## Test Plan
Tested locally.

### CODE REVIEW

File: src/App.vue [hunk 1]
```diff
@@ -1,11 +1,14 @@
 <template>
   <div id="header">
+    <div>
+      <LocaleSwitcher id="locale" class="hidden"></LocaleSwitcher>
```
Comment (deepansh96) [inline src/App.vue:4]:
```suggestion
      <LocaleSwitcher id="locale" v-show="false"></LocaleSwitcher>
```

**Review by deepansh96 — CHANGES_REQUESTED** [review]
Just one change suggested, can merge after that

File: src/App.vue (hunk 1 above)
Comment (dalmia) [reply src/App.vue:4]: Nice :+1:

Comment (dalmia) [reply src/App.vue:4]: This removes the element - does not make it invisible.

**Review by deepansh96 — APPROVED** [review]
