### PR TITLE
FIX: minor UI fixes

### LINKED ISSUE #377: Minor UI bugs
- option container becomes shorter width when in fullscreen and height > width
- image container takes too much space when in portrait + fullscreen mode
- image container width is too large
- flex-row unnecessarily specified
- spacing of image and MCQ box and subjective box was very hacky - made it neater
- subjective box was looking very weird in the preview mode in smaller screens
- skip video button has shadow but show video button doesn't

### PR DESCRIPTION
**Pull request by dalmia**
Fixes #377 

## Test Plan

- [x] Test Responsiveness
   - [ ] Laptop (1200px)
   - [ ] Tablet (760px)
   - [ ] Phone (320px)
- [ ] Cross-Browser Testing
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Safari
- [ ] ~Local Language Support~
- [ ] ~Wrote tests~
- [x] Tested locally
- [x] Tested on staging
- [ ] Tested on an actual physical phone
- [ ] Tested on production
- [ ] ~Check for bundle size [here](https://bundlephobia.com/) if adding a package~
- [x] Added relevant details like Labels/Projects/Milestones etc.

### CODE REVIEW

File: src/components/Player/ItemModal.vue [hunk 1]
```diff
@@ -266,7 +266,7 @@ export default {
         this.isPortrait = false;
         return;
       }
-      if (screen.availHeight > screen.availWidth) this.isPortrait = true;
+      if (screen.availHeight > 2 * screen.availWidth) this.isPortrait = true;
```
Comment (deepansh96) [inline src/components/Player/ItemModal.vue:269]:
```suggestion
      if (screen.availHeight > 1.5 * screen.availWidth) this.isPortrait = true;
```

**Review by deepansh96 — APPROVED** [review]
