### PR TITLE
FIX: tailwind installation

### LINKED ISSUE #113: Tailwind installation doesn't work

### PR DESCRIPTION
**Pull request by dalmia**
Fixes #113 
 
## Summary
Followed the [installation guide](https://tailwindcss.com/docs/installation#post-css-7-compatibility-build) to install Tailwind correctly.  

## Test Plan
Tested the classes of Tailwind in a dummy component

### CODE REVIEW

File: src/main.js [hunk 1]
```diff
@@ -7,10 +7,9 @@ import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
 import i18n from "./services/Localisation/i18n.js";
 import PrimeVue from "primevue/config";
```
Comment (deepansh96) [inline src/main.js:9]:
```suggestion
import "primevue/resources/themes/saga-blue/theme.css";
```

**Review by deepansh96 — APPROVED** [review]
