### PR TITLE
UI bugs 0.1.3

### LINKED ISSUE #265: UI Bugs for release 0.1.3
https://www.notion.so/avantifellows/v0-1-3-UI-bugs-06bbe19217f34a4fbebe5c4647b3ebdd

### PR DESCRIPTION
**Pull request by deepansh96**
Fixes #265

### CODE REVIEW

File: src/components/UI/Navigation/Paginator.vue [hunk 1]
```diff
@@ -70,6 +70,7 @@
             :key="pageNumber"
             :class="setPageButtonClass(pageNumber)"
             @click="setAndRouteToPage(pageNumber)"
+            :disabled="paginatorDetails.currentPage === pageNumber"
```
Comment (dalmia) [inline src/components/UI/Navigation/Paginator.vue:73]: disable first/previous/next/last buttons like this too.

File: src/App.vue [hunk 2]
```diff
@@ -130,13 +137,22 @@ export default {
         if (!isUserInWorkspace) this.$router.replace({ name: "Home" });
       }
     },
+    $route(to, from) {
+      // show user logged out toast when app is routed to login page
+      // and only when the logout action was not triggered by the user
+      if (to.name == "Login" && from.name != undefined && !this.userClickedLogout) {
+        this.toast.error(this.$t("error.auto_logout"));
+      }
+    },
```
Comment (dalmia) [inline src/App.vue:146]: better to include it in router/index.js

File: src/App.vue [hunk 3]
```diff
@@ -130,13 +137,22 @@ export default {
...
   },
   methods: {
     // object spread operator
     // https://vuex.vuejs.org/guide/state.html#object-spread-operator
     ...mapActions("auth", ["unsetAccessToken", "fetchAndUpdateUser"]),
     ...mapActions("sync", ["stopLoading"]),
-    logoutUser() {
+    logoutUser(isUserTriggered = false) {
+      // set whether the logout action as triggered by the user or not
+      this.userClickedLogout = isUserTriggered;
```
Comment (dalmia) [inline src/App.vue:155]: can first have separate function - clickLogout triggered by onclick where this param is set and then this function does not need to accept any param.

File: src/pages/Login.vue [hunk 4]
```diff
@@ -287,6 +287,7 @@ export default {
             this.invalidOtp = true;
             this.toast.error(this.$t("login.otp.incorrect"));
```
Comment (dalmia) [inline src/pages/Login.vue:288]: 1. both submit otp and google sign in button show loading spinner
2. while loading spinner, if someone leaves, pending is still true and so, spinner keeps running

File: src/router/index.js [hunk 5]
```diff
@@ -102,6 +103,16 @@ router.beforeEach((to, from, next) => {
   // clear all toasts whenever the route changes
   toast.clear();
 
+  // show auto logout toast
+  if (
+    to.name == "Login" &&
+    from.name != undefined &&
+    from.name != "Login" &&
+    to.params["userClickedLogout"] == "false"
```
Comment (dalmia) [inline src/router/index.js:111]: would be good to instead use this so that it doesn't break when `userClickedLogout` is not passed some time in the future (as we might forget this then):
```python
to.params.get("userClickedLogout")
```

Comment (deepansh96) [reply src/router/index.js:111]: Javascript doesn't have a `get` method
And I checked with not passing `userClickedLogout`, as it's a string,`to.params["userClickedLogout"] == "false"` just gives the output as a boolean `false` so it won't break

File: src/pages/Login.vue [hunk 6]
```diff
@@ -33,32 +33,22 @@
...
+        :disabled="!isSubmitOTPEnabled || submitOTPIconConfig.enabled"
+      ></icon-button>
       <!-- button to request resending OTP -->
       <icon-button
         @click="resendOtp"
         :titleConfig="resendOTPTitleConfig"
         :buttonClass="resendOTPButtonClass"
         class="mt-2"
-        :isDisabled="pending"
+        :isDisabled="pending || submitOTPIconConfig.enabled"
```
Comment (dalmia) [inline src/pages/Login.vue:51]: pending is not needed here right? - had added during the same PR when adding spinner to submit OTP

File: src/pages/Login.vue [hunk 7]
```diff
@@ -275,7 +270,7 @@ export default {
     },
     phoneLogin() {
       // invoked for logging in with Phone
-      this.startLoading();
+      this.submitOTPIconConfig.enabled = true;
```
Comment (dalmia) [inline src/pages/Login.vue:273]: i think it is better to have a data property: `isSubmitOTPInProgress` and then, set `submitOTPIconConfig.enabled` = `isSubmitOTPInProgress`. Code makes more sense then.

File: src/pages/Login.vue [hunk 8]
```diff
@@ -144,16 +144,19 @@ export default {
       toast: useToast(), // use the toast component
       warningIcon: require("@/assets/images/exclamation-circle-solid.svg"),
       isGoogleAuthDisabled: true, // whether the google auth button is disabled
-      submitOTPIconConfig: {
-        // config for the loading icon on the submit otp button
-        enabled: false,
-        iconName: "spinner-solid",
-        iconClass: "animate-spin h-4 object-scale-down text-white",
-      },
+      isSubmitOTPInProgress: false, // whether submit OTP button is in loading mode or not
```
Comment (dalmia) [inline src/pages/Login.vue:147]:
```suggestion
      isSubmitOTPInProgress: false, // whether the OTP has been submitted and is being verified

```
